#!/bin/bash
host=`hostname`
if [ ! ${host:0:3} == "gra" ]
then
	echo "Please ssh to graham.sharcnet.ca before using $0" >&2
	exit 1
fi

execpath=`dirname $0`
execpath=`realpath $execpath`

app_list=$execpath/bids-apps.tsv



#run a pipeline job on the cluster
#pipeline jobs take subjids as args

if [ ! -n "$SINGULARITY_OPTS" ]
then
	echo "SINGULARITY_OPTS not defined! exiting..." >&2
	exit 1
fi

cmd=$0
cmdname=${cmd##*/}


if [ "$#" -lt 5 ]
then 
   echo""
   echo "=========================================================================="
   echo "Interface for running bids apps on the cluster with singularity"
   echo ""
   echo "  Loops through an input subject_list_txt (txt with subj id on each line)"
   echo "  Can be used to run scripts that generally take command-line parameters as:"
   echo ""
   echo "Usage: $cmdname <optional flags> <app_name> <version> <bids_dir> <output_dir> <participant/group> <app options>"
   echo ""
   echo "Available apps:"
	cat $app_list | awk -F '\t' '{print $1 "\t"  $2}'
   echo ""
   echo "optional flags:"
   echo ""
   echo " -s <subjid> : single-subject mode, run on a single subject (must be in subjlist) instead"
   echo " -t : test-mode, don/'t actually submit any jobs"
   echo ""
   echo " Required resources:"
   echo " -j <job-template> :  sets requested resources"
   echo "	Regular (default):	8core/32gb/24h"
   echo "	LongSkinny:		1core/4gb/72h"
   echo "	ShortFat:		32core/128gb/3h"
   echo ""
   echo ""
   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
   echo ""

  exit 1
fi

job_template=Regular
depends=""
singlesubj=""
testmode=0


output_dir=.

while getopts "j:d:s:tl:" options; do
 case $options in
    j ) echo "	Using job template: $OPTARG" >&2
	job_template=$OPTARG;;
    d ) echo "	Using dependencies: $OPTARG" >&2
	depends=$OPTARG;;
    l ) echo "	Using subject list: $OPTARG" >&2
	subjlist=$OPTARG;;
    s ) echo "	Using single subject: $OPTARG" >&2
	singlesubj=$OPTARG;;
    t ) echo "	Using test-mode (no submit jobs)" >&2
	testmode=1;;
    * ) usage
	exit 1;;
 esac
done

shift $((OPTIND-1))

bids_app_dir=$SINGULARITY_DIR/bids-apps

app_name=$1
tag=$2
bids_dir=`realpath $3`
out_dir=$4
level=$5

mkdir -p $out_dir
out_dir=`realpath $out_dir`

shift 5
options=$@

repo=`grep "${app_name}	${tag}" $app_list | awk -F '\t' '{print $3}'`

if [ ! -n "$repo"  ]
then
	echo "${app_name} ${tag} does not exist in bids-app list!" 
	exit 1
fi

base_opts=`grep "${app_name}	${tag}" $app_list | awk -F '\t' '{print $4}'`
singularity_image=$bids_app_dir/${repo}_${app_name}_${tag}.img

if [ ! -e $singularity_image ]
 then 
	 echo "Singularity image: $singularity_image  not found,"
	echo "   run deploy_bids-apps first on your local machine"
	 exit 1
 fi



list=$bids_dir/participants.tsv

if [ ! -e $list ]
then
 echo "$list does not exist, quitting!"
 exit 0
fi

N=`tail -n +2 $list | wc -l`

#TODO modify this to accept a subject list instead of just single subjects
if [ ! -n "$singlesubj" ]
then
	indices="1-$N"  # all lines in subjlist, 1 to N
else
	N_matched=`grep -n sub-$singlesubj $list | wc -l` 
	if [ "$N_matched" == 1 ]
	then
		ind_subj=`grep -n sub-$singlesubj $list`
		indices=${ind_subj%%:*}
	fi

	if [ "$N_matched" == 0 ]
	then
		echo "single_subj: $singlesubj does not match any subjids in $list!" >&2
		exit 1
	fi

	if [ "$N_matched" -gt 1 ]
	then
		echo "single_subj: $singlesubj matches multiple subjids in $subjlist!" >&2
		exit 1
	fi
fi

job_dir=$output_dir/jobs
mkdir -p $job_dir

job=$job_dir/$app_name.job

execpath=`dirname $0`
execpath=`realpath $execpath`
cp $execpath/job-templates/${job_template}.job $job  

echo "#SBATCH --job-name=$app_name" >> $job


if [ "$level" == "participant" ]
then
	#submit with array, using subj and subjlist, indexed by line number (1-N)
	echo "#SBATCH --output=$job_dir/${app_name}.$level.%A_%a.out" >> $job
	echo "#SBATCH --array=$indices" >> $job
	
	echo "subj=\`head -n \$SLURM_ARRAY_TASK_ID `realpath $list` | awk '{print \$1}' | tail -n 1\`" >> $job
	echo "echo SINGULARITY_IMAGE: $singularity_image" >> $job
	echo "echo CMD: --participant_label=\$subj $base_opts $options $bids_dir $out_dir $level" >>$job
	echo "echo START_TIME: \`date\`" >>$job
	echo singularity run $SINGULARITY_OPTS $singularity_image --participant_label=\$subj $base_opts $options $bids_dir $out_dir $level  >> $job
	echo "echo END_TIME: \`date\`" >>$job

	echo -n "		Queuing participant-level job, $depends ... " >&2
else
	#submit without arrays, for group level
	echo "#SBATCH --output=$job_dir/${app_name}.$level.%A.out" >> $job
	echo "echo SINGULARITY_IMAGE: $singularity_image" >> $job
	echo "echo CMD: $base_opts $options $bids_dir $out_dir $level" >>$job
	echo "echo START_TIME: \`date\`" >>$job
	echo singularity run $SINGULARITY_OPTS $singularity_image $base_opts $options $bids_dir $out_dir $level  >> $job
	echo "echo END_TIME: \`date\`" >>$job
	
	
	echo -n "		Queuing group-level job, $depends ... " >&2
fi


if [ "$testmode" == 0 ]
then
message=`sbatch --dependency=$depends $job`


# Extract job identifier from SLURM's message.
if ! echo ${message} | grep -q "[1-9][0-9]*$"; then 
	echo "Job(s) submission failed." >&2
	echo ${message} >&2
	exit 1
else
	jobid=$(echo ${message} | grep -oh "[1-9][0-9]*$")
fi
echo "jobid=$jobid" >&2
exec_job=$job_dir/$app_name.$jobid.job

#copy instance of this job script for provenance
cp  $job $exec_job

else
	jobid=$RANDOM
	echo "fake-jobid=$jobid  (test-mode: no jobs submitted)" >&2

fi

echo $jobid

exit 0
