#!/bin/bash

execpath=`dirname $0`
execpath=`realpath $execpath`


source $execpath/00_init.sh
if [ ! "$?" = 0 ]
then
	echo "Error initializing neuroglia-helpers, quitting $0"
	exit 1
fi



cfmm2tar_img=`shub-cache shub://khanlab/cfmm2tar:v0.0.1i`

singularity run -B /cvmfs:/cvmfs -B /project:/project -B /scratch:/scratch -B /localscratch:/localscratch $cfmm2tar_img $@
