#!/bin/bash

remote_dir=~/graham/singularity/bids-apps

execpath=`dirname $0`
execpath=`realpath $execpath`

app_list=$execpath/bids-apps.tsv

Nlines=`cat $app_list | wc -l`

for i in `seq 2 $Nlines`
do
 app=`cat $app_list | head -n $i | tail -n 1 | awk  -F '\t' '{print $1}'`
 tag=`cat $app_list | head -n $i | tail -n 1 | awk  -F '\t' '{print $2}'`
 repo=`cat $app_list | head -n $i | tail -n 1 | awk  -F '\t' '{print $3}'`
 base_opts=`cat $app_list | head -n $i | tail -n 1 | awk  -F '\t' '{print $4}'`
 docker_name=${repo}/${app}:${tag}
 out_name=${repo}_${app}_${tag}.img
 out_img=$remote_dir/$out_name

 if [ ! -e $out_img ]
 then
 
 tmpdir=/tmp/singularity$RANDOM
 mkdir -p $tmpdir
 echo "Pulling docker://$docker_name ..."
 $execpath/docker2singularity $docker_name $tmpdir

 tmp_img=`ls -tr $tmpdir/${repo}_${app}_${tag}*.img | tail -n 1`
 
 echo "Copying to remote folder $out_img ..."
 rsync --info=progress2 $tmp_img $out_img 
 rm -rf $tmpdir

 else
  echo Skipping $out_img, already exists ...
 fi

done
