#!/bin/bash

if [ "$#" -lt 2 ]
then
  echo "Usage: $0 <in docker hub image> <output singularity image dir>"
  exit 0
fi

docker_image=$1
out_dir=$2


  docker run \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v $out_dir:/output \
 --privileged -t --rm \
 singularityware/docker2singularity \
$docker_image
