#!/bin/bash
host=`hostname`
if [ ! ${host:0:3} == "gra" ]
then
	echo "Please ssh to graham.sharcnet.ca before using $0" >&2
	exit 1
fi



#run a pipeline job on the cluster
#pipeline jobs take subjids as args

if [ ! -n "$SINGULARITY_IMG" ]
then
	echo "SINGULARITY_IMG not defined! exiting..." >&2
	exit 1
fi

if [ ! -n "$SINGULARITY_OPTS" ]
then
	echo "SINGULARITY_OPTS not defined! exiting..." >&2
	exit 1
fi

cmd=$0
cmdname=${cmd##*/}


if [ "$#" -lt 1 ]
then 
   echo""
   echo "=========================================================================="
   echo "Interface for submitting a single cluster job with singularity"
   echo ""
   echo "--------------------------------------------------------------------------"
   echo "Usage: $cmdname <optional flags>  <command to run>"
   echo "--------------------------------------------------------------------------"
   echo ""
   echo "optional flags:"
   echo ""
   echo " -t : test-mode, don/'t actually submit any jobs"
   echo ""
   echo " Required resources:"
   echo " -j <job-template> :  sets requested resources"
   echo "	Regular (default):	8core/32gb/24h"
   echo "	LongSkinny:		1core/4gb/72h"
   echo "	ShortFat:		32core/128gb/3h"
   echo ""
   echo ""
   echo " SLURM Job dependencies for pipelining (man sbatch for more details):"
   echo "  -d aftercorr:jobid[:jobid]	: each subj depends on completed subj in submitted job ids"  
   echo "  -d afterok:jobid[:jobid]	: each subj depends on all completed subj in submitted job id"
   echo ""

  exit 1
fi

job_template=Regular
depends=""
testmode=0


output_dir=.

while getopts "j:d:t" options; do
 case $options in
    j ) echo "	Using job template: $OPTARG" >&2
	job_template=$OPTARG;;
    d ) echo "	Using dependencies: $OPTARG" >&2
	depends=$OPTARG;;
    t ) echo "	Using test-mode (no submit jobs)" >&2
	testmode=1;;
    * ) usage
	exit 1;;
 esac
done


shift $((OPTIND-1))

run_cmd=$1

cmdname=${run_cmd##*/} #remove up to leading slash

echo $cmdname >&2


job_dir=$output_dir/jobs
mkdir -p $job_dir

job=$job_dir/$cmdname.job

execpath=`dirname $0`
execpath=`realpath $execpath`
cp $execpath/job-templates/${job_template}.job $job  

echo "#SBATCH --job-name=$cmdname" >> $job
echo "#SBATCH --output=$job_dir/${cmdname}.%A.out" >> $job
echo "echo SINGULARITY_IMG: $SINGULARITY_IMG" >> $job
echo "echo CMD: $@" >>$job
echo "echo START_TIME: \`date\`" >>$job
echo cd `pwd` >> $job
echo singularity exec $SINGULARITY_OPTS $SINGULARITY_IMG $@ >> $job
echo "echo END_TIME: \`date\`" >>$job
echo -n "		Queuing job, $depends ... " >&2


if [ "$testmode" == 0 ]
then
message=`sbatch --dependency=$depends $job`


# Extract job identifier from SLURM's message.
if ! echo ${message} | grep -q "[1-9][0-9]*$"; then 
	echo "Job(s) submission failed." >&2
	echo ${message} >&2
	exit 1
else
	jobid=$(echo ${message} | grep -oh "[1-9][0-9]*$")
fi
echo "jobid=$jobid" >&2
exec_job=$job_dir/$cmdname.$jobid.job

#copy instance of this job script for provenance
cp  $job $exec_job

else
	jobid=$RANDOM
	echo "fake-jobid=$jobid  (test-mode: no jobs submitted)" >&2

fi

echo $jobid

exit 0
