#!/bin/bash

host=`hostname`

name=neuroglia_interactive

if [ ${host:0:3} == "gra" ]
then
	echo running on graham
	salloc -J $name  -D `pwd` --time=1:00:00 --cpus-per-task=8 --ntasks=1 --mem=32000 --account=rrg-akhanf  neurogliaShell #singularity shell $SINGULARITY_OPTS $SINGULARITY_IMG $@
else

	echo "Please ssh to graham.sharcnet.ca before using $0"
	exit -1
fi

