#!/bin/bash

host=`hostname`

name=neuroglia_interactive

if [ ${host:0:3} == "gra" ]
then
	echo running on graham
	if [ "$1" == "-Y" ] 
	then
		echo using visualization
		salloc -J $name --x11 -D `pwd` --time=3:00:00 --cpus-per-task=8 --ntasks=1 --mem=32000 --account=rrg-akhanf
	
	elif [ "$1" == "-gpu" ]
	then
		# Uses account def-akhanf-ab_gpu
		echo using gpu
		salloc -J $name -D `pwd` --time=3:00:00 --cpus-per-task=8 --ntasks=1 --mem=32000 --gres=gpu:1 --account=def-akhanf-ab_gpu
	
	else
		salloc -J $name  -D `pwd` --time=3:00:00 --cpus-per-task=8 --ntasks=1 --mem=32000 --account=rrg-akhanf  
	fi
else

	echo "Please ssh to graham.sharcnet.ca before using $0"
	exit -1
fi

