#!/bin/bash

job=$1
csv=$2
if [ "$#" -lt 2 ]
then
echo "UsagE: $0 <jobid> <csv>"
exit 1
fi

fmt="JobID"; for field in `sacct --helpformat`; do fmt="$fmt,$field";  done
sacct --format=$fmt -p --delimiter="," > $csv
