#!/bin/bash
if [ "$#" -lt 2 ]
then
echo "Usage: $0 <job list files (submits in order with dependencies)"
exit 0
fi

depends="afterany"

for list in $@
do

 dep=$(joblistSubmit  $list -d $depends)

 depends="$depends:$dep"

done

