#!/bin/bash


execpath=`dirname $0`
execpath=`realpath $execpath`


source $execpath/00_init.sh
if [ ! "$?" = 0 ]
then
	echo "Error initializing neuroglia-helpers, quitting $0"
	exit 1
fi



tar2bids_img=`shub-cache docker://khanlab/tar2bids:v0.0.3d`

echo "CMD: singularity run $SINGULARITY_OPTS $tar2bids_img $@"
singularity run $SINGULARITY_OPTS  $tar2bids_img $@

