#!/bin/bash


tar2bids_img=`shub-cache docker://khanlab/tar2bids:v0.0.3d`

echo "CMD: singularity run $SINGULARITY_OPTS -B /localscratch:/localscratch $tar2bids_img $@"
singularity run $SINGULARITY_OPTS -B /localscratch:/localscratch $tar2bids_img $@

