#!/bin/bash

execpath=`dirname $0`
execpath=`realpath $execpath`


source $execpath/00_init.sh
if [ ! "$?" = 0 ]
then
	echo "Error initializing neuroglia-helpers, quitting $0"
	exit 1
fi


singularity run $SINGULARITY_OPTS `shub-cache docker://bids/validator:0.27.10` $@
